const DashboardActionTypes = {

    // dashboard list 
    GET_DASHBOARD_LIST: '@@GET_DASHBOARD_LIST',
    DASHBOARD_LIST_LOADING: '@@DASHBOARD_LIST/LOADING',
    DASHBOARD_LIST_SUCCESS: '@@DASHBOARD_LIST/SUCESS',
    DASHBOARD_LIST_ERROR: '@@DASHBOARD_LIST/ERROR',

    //today order list 
    GET_TODAY_ORDER_LIST: '@@GET_TODAY_ORDER_LIST',
    TODAY_ORDER_LIST_LOADING: '@@TODAY_ORDER_LIST/LOADING',
    TODAY_ORDER_LIST_SUCCESS: '@@TODAY_ORDER_LIST/SUCESS',
    TODAY_ORDER_LIST_ERROR: '@@TODAY_ORDER_LIST/ERROR',

    //order status
    GET_ORDER_STATUS: '@@GET_ORDER_STATUS',
    ORDER_STATUS_LOADING: '@@ORDER_STATUS/LOADING',
    ORDER_STATUS_SUCCESS: '@@ORDER_STATUS/SUCESS',
    ORDER_STATUS_ERROR: '@@ORDER_STATUS/ERROR',

}
export default DashboardActionTypes