const AssignedPackageActionTypes = {

    // start list 
    GET_ASSIGNED_PACKAGE_LIST: '@@GET_ASSIGNED_PACKAGE_LIST',
    ASSIGNED_PACKAGE_LIST_LOADING: '@@ASSIGNED_PACKAGE_LIST/LOADING',
    ASSIGNED_PACKAGE_LIST_SUCCESS: '@@ASSIGNED_PACKAGE_LIST/SUCESS',
    ASSIGNED_PACKAGE_LIST_ERROR: '@@ASSIGNED_PACKAGE_LIST/ERROR',


    // start create 
    CREATE_ASSIGNED_PACKAGE: '@@CREATE_ASSIGNED_PACKAGE',
    ASSIGNED_PACKAGE_CREATE_LOADING: '@@ASSIGNED_PACKAGE_CREATE/LOADING',
    ASSIGNED_PACKAGE_CREATE_SUCESS: '@@ASSIGNED_PACKAGE_CREATE/SUCESS',
    ASSIGNED_PACKAGE_CREATE_RESET: '@@ASSIGNED_PACKAGE_CREATE/RESET',
    ASSIGNED_PACKAGE_CREATE_ERROR: '@@ASSIGNED_PACKAGE_CREATE/ERROR',

    // start delete
    DELETE_ASSIGNED_PACKAGE: '@@DELETE_ASSIGNED_PACKAGE',
    ASSIGNED_PACKAGE_DELETE_LOADING: '@@ASSIGNED_PACKAGE_DELETE/LOADING',
    ASSIGNED_PACKAGE_DELETE_SUCESS: '@@ASSIGNED_PACKAGE_DELETE/SUCESS',
    ASSIGNED_PACKAGE_DELETE_RESET: '@@ASSIGNED_PACKAGE_DELETE/RESET',
    ASSIGNED_PACKAGE_DELETE_ERROR: '@@ASSIGNED_PACKAGE_DELETE/ERROR',


}
export default AssignedPackageActionTypes