const PromoCouponActionTypes = {

    // start promo coupon list 
    GET_PROMO_COUPON_LIST: '@@GET_PROMO_COUPON_LIST',
    PROMO_COUPON_LIST_LOADING: '@@PROMO_COUPON_LIST/LOADING',
    PROMO_COUPON_LIST_SUCCESS: '@@PROMO_COUPON_LIST/SUCESS',
    PROMO_COUPON_LIST_ERROR: '@@PROMO_COUPON_LIST/ERROR',

    // start promo coupon create 
    CREATE_PROMO_COUPON: '@@CREATE_PROMO_COUPON',
    PROMO_COUPON_CREATE_LOADING: '@@PROMO_COUPON_CREATE/LOADING',
    PROMO_COUPON_CREATE_SUCCESS: '@@PROMO_COUPON_CREATE/SUCESS',
    PROMO_COUPON_CREATE_RESET: '@@PROMO_COUPON_CREATE/RESET',
    PROMO_COUPON_CREATE_ERROR: '@@PROMO_COUPON_CREATE/ERROR',

    // start promo coupon detail 
    DETAIL_PROMO_COUPON: '@@DETAIL_PROMO_COUPON',
    PROMO_COUPON_DETAIL_LOADING: '@@PROMO_COUPON_DETAIL/LOADING',
    PROMO_COUPON_DETAIL_SUCCESS: '@@PROMO_COUPON_DETAIL/SUCESS',
    PROMO_COUPON_DETAIL_RESET: '@@PROMO_COUPON_DETAIL/RESET',
    PROMO_COUPON_DETAIL_ERROR: '@@PROMO_COUPON_DETAIL/ERROR',

    // start promo coupon update
    UPDATE_PROMO_COUPON: '@@UPDATE_PROMO_COUPON',
    PROMO_COUPON_UPDATE_LOADING: '@@PROMO_COUPON_UPDATE/LOADING',
    PROMO_COUPON_UPDATE_SUCCESS: '@@PROMO_COUPON_UPDATE/SUCESS',
    PROMO_COUPON_UPDATE_RESET: '@@PROMO_COUPON_UPDATE/RESET',
    PROMO_COUPON_UPDATE_ERROR: '@@PROMO_COUPON_UPDATE/ERROR',

    // start promo coupon delete 
    DELETE_PROMO_COUPON: '@@DELETE_PROMO_COUPON',
    PROMO_COUPON_DELETE_LOADING: '@@PROMO_COUPON_DELETE/LOADING',
    PROMO_COUPON_DELETE_SUCCESS: '@@PROMO_COUPON_DELETE/SUCESS',
    PROMO_COUPON_DELETE_RESET: '@@PROMO_COUPON_DELETE/RESET',
    PROMO_COUPON_DELETE_ERROR: '@@PROMO_COUPON_DELETE/ERROR',


}
export default PromoCouponActionTypes