const RetailProductWiseReportListActionTypes = {

    // start Monthly Report List 
    GET_RETAIL_PRODUCT_WISE_REPORT_LIST: '@@GET_RETAIL_PRODUCT_WISE_REPORT_LIST',
    RETAIL_PRODUCT_WISE_REPORT_LIST_LOADING: '@@RETAIL_PRODUCT_WISE_REPORT_LIST/LOADING',
    RETAIL_PRODUCT_WISE_REPORT_LIST_SUCCESS: '@@RETAIL_PRODUCT_WISE_REPORT_LIST/SUCESS',
    RETAIL_PRODUCT_WISE_REPORT_LIST_ERROR: '@@RETAIL_PRODUCT_WISE_REPORT_LIST/ERROR'

}
export default RetailProductWiseReportListActionTypes;