const PickupRequestActionTypes = {

    GET_PICKUP_REQUEST_LIST: '@@GET_PICKUP_REQUEST_LIST',
    PICKUP_REQUEST_LIST_LOADING: '@@PICKUP_REQUEST_LIST/LOADING',
    PICKUP_REQUEST_LIST_SUCCESS: '@@PICKUP_REQUEST_LIST/SUCESS',
    PICKUP_REQUEST_LIST_ERROR: '@@PICKUP_REQUEST_LIST/ERROR',

    CREATE_PICKUP_REQUEST: '@@CREATE_PICKUP_REQUEST',
    PICKUP_REQUEST_CREATE_LOADING: '@@PICKUP_REQUEST_CREATE/LOADING',
    PICKUP_REQUEST_CREATE_SUCCESS: '@@PICKUP_REQUEST_CREATE/SUCESS',
    PICKUP_REQUEST_CREATE_RESET: '@@PICKUP_REQUEST_CREATE/RESET',

    PICKUP_REQUEST_CREATE_ERROR: '@@PICKUP_REQUEST_CREATE/ERROR',

}
export default PickupRequestActionTypes