const PaymentChargesActionTypes = {

    // start list 
    GET_PAYMENT_CHARGES_LIST: '@@GET_PAYMENT_CHARGES_LIST',
    PAYMENT_CHARGES_LIST_LOADING: '@@PAYMENT_CHARGES_LIST/LOADING',
    PAYMENT_CHARGES_LIST_SUCCESS: '@@PAYMENT_CHARGES_LIST/SUCESS',
    PAYMENT_CHARGES_LIST_ERROR: '@@PAYMENT_CHARGES_LIST/ERROR',


    // start create 
    CREATE_PAYMENT_CHARGES: '@@CREATE_PAYMENT_CHARGES',
    PAYMENT_CHARGES_CREATE_LOADING: '@@PAYMENT_CHARGES_CREATE/LOADING',
    PAYMENT_CHARGES_CREATE_SUCESS: '@@PAYMENT_CHARGES_CREATE/SUCESS',
    PAYMENT_CHARGES_CREATE_ERROR: '@@PAYMENT_CHARGES_CREATE/ERROR',
    PAYMENT_CHARGES_CREATE_RESET: '@@PAYMENT_CHARGES_CREATE/RESET',


    // start update 
    UPDATE_PAYMENT_CHARGES: '@@UPDATE_PAYMENT_CHARGES',
    PAYMENT_CHARGES_UPDATE_LOADING: '@@PAYMENT_CHARGES_UPDATE/LOADING',
    PAYMENT_CHARGES_UPDATE_SUCESS: '@@PAYMENT_CHARGES_UPDATE/SUCESS',
    PAYMENT_CHARGES_UPDATE_ERROR: '@@PAYMENT_CHARGES_UPDATE/ERROR',
    PAYMENT_CHARGES_UPDATE_RESET: '@@PAYMENT_CHARGES_UPDATE/RESET',


    // start details 
    REMOVE_PAYMENT_CHARGES: '@@REMOVE_PAYMENT_CHARGES',
    PAYMENT_CHARGES_REMOVE_LOADING: '@@PAYMENT_CHARGES_REMOVE/LOADING',
    PAYMENT_CHARGES_REMOVE_SUCESS: '@@PAYMENT_CHARGES_REMOVE/SUCESS',
    PAYMENT_CHARGES_REMOVE_ERROR: '@@PAYMENT_CHARGES_REMOVE/ERROR',
    PAYMENT_CHARGES_REMOVE_RESET: '@@PAYMENT_CHARGES_REMOVE/RESET',

}
export default PaymentChargesActionTypes