const DiscountChargesActionTypes = {

    // start discount charges list 
    GET_DISCOUNT_CHARGES_LIST: '@@GET_DISCOUNT_CHARGES_LIST',
    DISCOUNT_CHARGES_LIST_LOADING: '@@DISCOUNT_CHARGES_LIST/LOADING',
    DISCOUNT_CHARGES_LIST_SUCCESS: '@@DISCOUNT_CHARGES_LIST/SUCESS',
    DISCOUNT_CHARGES_LIST_ERROR: '@@DISCOUNT_CHARGES_LIST/ERROR',

    // start discount charges create 
    CREATE_DISCOUNT_CHARGES: '@@CREATE_DISCOUNT_CHARGES',
    DISCOUNT_CHARGES_CREATE_LOADING: '@@DISCOUNT_CHARGES_CREATE/LOADING',
    DISCOUNT_CHARGES_CREATE_SUCESS: '@@DISCOUNT_CHARGES_CREATE/SUCESS',
    DISCOUNT_CHARGES_CREATE_RESET: '@@DISCOUNT_CHARGES_CREATE/RESET',
    DISCOUNT_CHARGES_CREATE_ERROR: '@@DISCOUNT_CHARGES_CREATE/ERROR',

    // start discount charges detail 
    DETAIL_DISCOUNT_CHARGES: '@@DETAIL_DISCOUNT_CHARGES',
    DISCOUNT_CHARGES_DETAIL_LOADING: '@@DISCOUNT_CHARGES_DETAIL/LOADING',
    DISCOUNT_CHARGES_DETAIL_SUCESS: '@@DISCOUNT_CHARGES_DETAIL/SUCESS',
    DISCOUNT_CHARGES_DETAIL_RESET: '@@DISCOUNT_CHARGES_DETAIL/RESET',
    DISCOUNT_CHARGES_DETAIL_ERROR: '@@DISCOUNT_CHARGES_DETAIL/ERROR',

    // start discount charges update
    UPDATE_DISCOUNT_CHARGES: '@@UPDATE_DISCOUNT_CHARGES',
    DISCOUNT_CHARGES_UPDATE_LOADING: '@@DISCOUNT_CHARGES_UPDATE/LOADING',
    DISCOUNT_CHARGES_UPDATE_SUCESS: '@@DISCOUNT_CHARGES_UPDATE/SUCESS',
    DISCOUNT_CHARGES_UPDATE_RESET: '@@DISCOUNT_CHARGES_UPDATE/RESET',
    DISCOUNT_CHARGES_UPDATE_ERROR: '@@DISCOUNT_CHARGES_UPDATE/ERROR',

    // start discount charges delete 
    DELETE_DISCOUNT_CHARGES: '@@DELETE_DISCOUNT_CHARGES',
    DISCOUNT_CHARGES_DELETE_LOADING: '@@DISCOUNT_CHARGES_DELETE/LOADING',
    DISCOUNT_CHARGES_DELETE_SUCESS: '@@DISCOUNT_CHARGES_DELETE/SUCESS',
    DISCOUNT_CHARGES_DELETE_RESET: '@@DISCOUNT_CHARGES_DELETE/RESET',
    DISCOUNT_CHARGES_DELETE_ERROR: '@@DISCOUNT_CHARGES_DELETE/ERROR',



}
export default DiscountChargesActionTypes