const HomePageSettingActionTypes = {

    // start home page setting list 
    GET_HOME_PAGE_SETTING_LIST: '@@GET_HOME_PAGE_SETTING_LIST',
    HOME_PAGE_SETTING_LIST_LOADING: '@@HOME_PAGE_SETTING_LIST/LOADING',
    HOME_PAGE_SETTING_LIST_SUCCESS: '@@HOME_PAGE_SETTING_LIST/SUCESS',
    HOME_PAGE_SETTING_LIST_ERROR: '@@HOME_PAGE_SETTING_LIST/ERROR',

    // start home page setting update 
    HOME_PAGE_SETTING_UPDATE: '@@GET_HOME_PAGE_SETTING_UPDATE',
    HOME_PAGE_SETTING_UPDATE_LOADING: '@@HOME_PAGE_SETTING_UPDATE/LOADING',
    HOME_PAGE_SETTING_UPDATE_SUCCESS: '@@HOME_PAGE_SETTING_UPDATE/SUCESS',
    HOME_PAGE_SETTING_UPDATE_ERROR: '@@HOME_PAGE_SETTING_UPDATE/ERROR',

}
export default HomePageSettingActionTypes