const BulkInvoiceActionTypes = {

    GET_BULK_INVOICE_LIST: '@@GET_BULK_INVOICE_LIST',
    BULK_INVOICE_LIST_LOADING: '@@BULK_INVOICE_LIST/LOADING',
    BULK_INVOICE_LIST_SUCCESS: '@@BULK_INVOICE_LIST/SUCESS',
    BULK_INVOICE_LIST_ERROR: '@@BULK_INVOICE_LIST/ERROR',

}
export default BulkInvoiceActionTypes