const ProductCategoryActionTypes = {

    // start list 
    GET_CATEGORY_LIST: '@@GET_CATEGORY_LIST',
    CATEGORY_LIST_LOADING: '@@CATEGORY_LIST/LOADING',
    CATEGORY_LIST_SUCCESS: '@@CATEGORY_LIST/SUCESS',
    CATEGORY_LIST_ERROR: '@@CATEGORY_LIST/ERROR',


    // start create 
    CREATE_CATEGORY: '@@CREATE_CATEGORY',
    CATEGORY_CREATE_LOADING: '@@CATEGORY_CREATE/LOADING',
    CATEGORY_CREATE_SUCESS: '@@CATEGORY_CREATE/SUCESS',
    CATEGORY_CREATE_RESET: '@@CATEGORY_CREATE/RESET',
    CATEGORY_CREATE_ERROR: '@@CATEGORY_CREATE/ERROR',


    // // start update 
    UPDATE_CATEGORY: '@@UPDATE_CATEGORY',
    CATEGORY_UPDATE_LOADING: '@@CATEGORY_UPDATE/LOADING',
    CATEGORY_UPDATE_SUCESS: '@@CATEGORY_UPDATE/SUCESS',
    CATEGORY_UPDATE_RESET: '@@CATEGORY_UPDATE/RESET',
    CATEGORY_UPDATE_ERROR: '@@CATEGORY_UPDATE/ERROR',

    // start delete 
    DELETE_CATEGORY: '@@DELETE_CATEGORY',
    CATEGORY_DELETE_LOADING: '@@CATEGORY_DELETE/LOADING',
    CATEGORY_DELETE_SUCESS: '@@CATEGORY_DELETE/SUCESS',
    CATEGORY_DELETE_ERROR: '@@CATEGORY_DELETE/ERROR',
    CATEGORY_DELETE_RESET: '@@CATEGORY_DELETE/RESETSET',

}

export default ProductCategoryActionTypes
