const IncomeReportActionTypes = {

    // start income Report List 
    GET_INCOME_REPORT_LIST: '@@GET_INCOME_REPORT_LIST',
    INCOME_REPORT_LIST_LOADING: '@@INCOME_REPORT_LIST/LOADING',
    INCOME_REPORT_LIST_SUCCESS: '@@INCOME_REPORT_LIST/SUCESS',
    INCOME_REPORT_LIST_ERROR: '@@INCOME_REPORT_LIST/ERROR',
    INCOME_REPORT_LIST_RESET: '@@INCOME_REPORT_LIST/RESET'


}
export default IncomeReportActionTypes;