const ProductListActionTypes = {
     GET_PRODUCT_LIST: '@@GET_PRODUCTS_LIST',
     PRODUCT_LIST_LOADING: '@@PRODUCTS_LIST/LOADING',
     PRODUCT_LIST_SUCCESS: '@@PRODUCTS_LIST/SUCESS',
     PRODUCT_LIST_ERROR: '@@PRODUCTS_LIST/ERROR'
};

export default ProductListActionTypes;
