const PaymentTypeActionTypes = {

    // start list 
    GET_PAYMENT_TYPE_LIST: '@@GET_PAYMENT_TYPE_LIST',
    PAYMENT_TYPE_LIST_LOADING: '@@PAYMENT_TYPE_LIST/LOADING',
    PAYMENT_TYPE_LIST_SUCCESS: '@@PAYMENT_TYPE_LIST/SUCESS',
    PAYMENT_TYPE_LIST_ERROR: '@@PAYMENT_TYPE_LIST/ERROR',


    // start create 
    CREATE_PAYMENT_TYPE: '@@PAYMENT_TYPE',
    PAYMENT_TYPE_CREATE_LOADING: '@@PAYMENT_TYPE_CREATE/LOADING',
    PAYMENT_TYPE_CREATE_SUCESS: '@@PAYMENT_TYPE_CREATE/SUCESS',
    PAYMENT_TYPE_CREATE_ERROR: '@@PAYMENT_TYPE_CREATE/ERROR',
    PAYMENT_TYPE_CREATE_RESET: '@@PAYMENT_TYPE_CREATE_RESET',

    // start update 
    UPDATE_PAYMENT_TYPE: '@@UPDATE_PAYMENT_TYPE',
    PAYMENT_TYPE_UPDATE_LOADING: '@@PAYMENT_TYPE_UPDATE/LOADING',
    PAYMENT_TYPE_UPDATE_SUCESS: '@@PAYMENT_TYPE_UPDATE/SUCESS',
    PAYMENT_TYPE_UPDATE_ERROR: '@@PAYMENT_TYPE_UPDATE/ERROR',
    PAYMENT_TYPE_UPDATE_RESET: '@@PAYMENT_TYPE_UPDATE/RESET',


    // start details 
    REMOVE_PAYMENT_TYPE: '@@REMOVE_PAYMENT_TYPE',
    PAYMENT_TYPE_REMOVE_LOADING: '@@PAYMENT_TYPE_REMOVE/LOADING',
    PAYMENT_TYPE_REMOVE_SUCESS: '@@PAYMENT_TYPE_REMOVE/SUCESS',
    PAYMENT_TYPE_REMOVE_ERROR: '@@PAYMENT_TYPE_REMOVE/ERROR',
    PAYMENT_TYPE_REMOVE_RESET: '@@PAYMENT_TYPE_REMOVE/RESET',

}
export default PaymentTypeActionTypes