const ExpensesReportActionTypes = {

    // start expenses Report List 
    GET_EXPENSE_REPORT_LIST: '@@GET_EXPENSE_REPORT_LIST',
    EXPENSE_REPORT_LIST_LOADING: '@@EXPENSE_REPORT_LIST/LOADING',
    EXPENSE_REPORT_LIST_SUCCESS: '@@EXPENSE_REPORT_LIST/SUCESS',
    EXPENSE_REPORT_LIST_ERROR: '@@EXPENSE_REPORT_LIST/ERROR',
    EXPENSE_REPORT_LIST_RESET: '@@EXPENSE_REPORT_LIST/RESET'


}
export default ExpensesReportActionTypes;