const DoordeshSettingActionTypes = {

    // start doordesh setting list 
    GET_DOORDESH_SETTING_LIST: '@@GET_DOORDESH_SETTING_LIST',
    DOORDESH_SETTING_LIST_LOADING: '@@DOORDESH_SETTING_LIST/LOADING',
    DOORDESH_SETTING_LIST_SUCCESS: '@@DOORDESH_SETTING_LIST/SUCESS',
    DOORDESH_SETTING_LIST_ERROR: '@@DOORDESH_SETTING_LIST/ERROR',

    // start doordesh Setting update
    DOORDESH_SETTING_UPDATE: '@@DOORDESH_SETTING_UPDATE',
    DOORDESH_SETTING_UPDATE_LOADING: '@@DOORDESH_SETTING_UPDATE/LOADING',
    DOORDESH_SETTING_UPDATE_SUCCESS: '@@DOORDESH_SETTING_UPDATE/SUCESS',
    DOORDESH_SETTING_UPDATE_ERROR: '@@DOORDESH_SETTING_UPDATE/ERROR',
    DOORDESH_SETTING_UPDATE_RESET: "@@DOORDESH_SETTING_UPDATE/RESET"

}
export default DoordeshSettingActionTypes