const ProductPriceActionTypes = {

    // start price list 
    GET_PRICE_LIST: '@@GET_PRICE_LIST',
    PRICE_LIST_LOADING: '@@PRICE_LIST/LOADING',
    PRICE_LIST_SUCCESS: '@@PRICE_LIST/SUCESS',
    PRICE_LIST_ERROR: '@@PRICE_LIST/ERROR',


    // start price create 
    CREATE_PRICE: '@@CREATE_PRICE',
    PRICE_CREATE_LOADING: '@@PRICE_CREATE/LOADING',
    PRICE_CREATE_SUCESS: '@@PRICE_CREATE/SUCESS',
    PRICE_CREATE_ERROR: '@@PRICE_CREATE/ERROR',


    // // start price update 
    UPDATE_PRICE: '@@UPDATE_PRICE',
    PRICE_UPDATE_LOADING: '@@PRICE_UPDATE/LOADING',
    PRICE_UPDATE_SUCESS: '@@PRICE_UPDATE/SUCESS',
    PRICE_UPDATE_ERROR: '@@PRICE_UPDATE/ERROR',

    // start item list 
    GET_ITEM_LIST: '@@GET_ITEM_LIST',
    ITEM_LIST_LOADING: '@@ITEM_LIST/LOADING',
    ITEM_LIST_SUCCESS: '@@ITEM_LIST/SUCESS',
    ITEM_LIST_ERROR: '@@ITEM_LIST/ERROR',


    // start item create 
    CREATE_ITEM: '@@CREATE_ITEM',
    ITEM_CREATE_LOADING: '@@ITEM_CREATE/LOADING',
    ITEM_CREATE_SUCESS: '@@ITEM_CREATE/SUCESS',
    ITEM_CREATE_ERROR: '@@ITEM_CREATE/ERROR',


    // // start item update 
    UPDATE_ITEM: '@@UPDATE_ITEM',
    ITEM_UPDATE_LOADING: '@@ITEM_UPDATE/LOADING',
    ITEM_UPDATE_SUCESS: '@@ITEM_UPDATE/SUCESS',
    ITEM_UPDATE_ERROR: '@@ITEM_UPDATE/ERROR',


    // start details 
    DETAILS_ITEM: '@@DETAILS_ITEM',
    ITEM_DETAILS_LOADING: '@@ITEM_ITEM/LOADING',
    ITEM_DETAILS_SUCESS: '@@ITEM_DETAILS/SUCESS',
    ITEM_DETAILS_ERROR: '@@ITEM_DETAILS/ERROR',
    ITEM_DETAILS_RESET: '@@ITEM_DETAILS/RESET',


    // start delete 
    DELETE_ITEM: '@@DELETE_ITEM',
    ITEM_DELETE_LOADING: '@@ITEM_DELETE/LOADING',
    ITEM_DELETE_SUCESS: '@@ITEM_DELETE/SUCESS',
    ITEM_DELETE_ERROR: '@@ITEM_DELETE/ERROR',
    ITEM_DELETE_RESET: '@@ITEM_DELETE/RESETSET',
}

export default ProductPriceActionTypes
