const TaxCollectionReportListActionTypes = {

    // start TAX COLLECTION REPORT 
    GET_TAX_COLLECTION_REPORT_LIST: '@@GET_TAX_COLLECTION_REPORT_LIST',
    TAX_COLLECTION_REPORT_LIST_LOADING: '@@TAX_COLLECTION_REPORT_LIST/LOADING',
    TAX_COLLECTION_REPORT_LIST_SUCCESS: '@@TAX_COLLECTION_REPORT_LIST/SUCESS',
    TAX_COLLECTION_REPORT_LIST_ERROR: '@@TAX_COLLECTION_REPORT_LIST/ERROR'

}
export default TaxCollectionReportListActionTypes;