const PaymentSettingActionTypes = {

    // start list 
    GET_PAYMENT_SETTING_LIST: '@@GET_PAYMENT_SETTING_TYPE_LIST',
    PAYMENT_SETTING_LIST_LOADING: '@@PAYMENT_SETTING_LIST/LOADING',
    PAYMENT_SETTING_LIST_SUCCESS: '@@PAYMENT_SETTING_LIST/SUCESS',
    PAYMENT_SETTING_LIST_ERROR: '@@PAYMENT_SETTING_LIST/ERROR',



}
export default PaymentSettingActionTypes;