const ServiceCategoryActionTypes = {
    // start list
    GET_SERVICE_CATEGORY_LIST: '@@GET_SERVICE_CATEGORY_LIST',
    SERVICE_CATEGORY_LIST_LOADING: '@@SERVICE_CATEGORY_LIST/LOADING',
    SERVICE_CATEGORY_LIST_SUCCESS: '@@SERVICE_CATEGORY_LIST/SUCESS',
    SERVICE_CATEGORY_LIST_ERROR: '@@SERVICE_CATEGORY_LIST/ERROR',

    // start create
    CREATE_SERVICE_CATEGORY: '@@CREATE_SERVICE_CATEGORY',
    SERVICE_CATEGORY_CREATE_LOADING: '@@SERVICE_CATEGORY_CREATE_LOADING/LOADING',
    SERVICE_CATEGORY_CREATE_SUCESS: '@@SERVICE_CATEGORY_CREATE_SUCESS/SUCESS',
    SERVICE_CATEGORY_CREATE_ERROR: '@@SERVICE_CATEGORY_CREATE_ERROR/ERROR',
    SERVICE_CATEGORY_CREATE_RESET: '@@SERVICE_CATEGORY_CREATE/RESETSET',

    // start update
    UPDATE_SERVICE_CATEGORY: '@@UPDATE_SERVICE_CATEGORY',
    SERVICE_CATEGORY_UPDATE_LOADING: '@@SERVICE_CATEGORY_UPDATE_LOADING/LOADING',
    SERVICE_CATEGORY_UPDATE_SUCESS: '@@SERVICE_CATEGORY_UPDATE_SUCESS/SUCESS',
    SERVICE_CATEGORY_UPDATE_ERROR: '@@SERVICE_CATEGORY_UPDATE_ERROR/ERROR',
    SERVICE_CATEGORY_UPDATE_RESET: '@@SERVICE_CATEGORY_UPDATE/RESETSET',

    // start delete
    DELETE_SERVICE_CATEGORY: '@@DELETE_SERVICE_CATEGORY',
    SERVICE_CATEGORY_DELETE_LOADING: '@@SERVICE_CATEGORY_DELETE/LOADING',
    SERVICE_CATEGORY_DELETE_SUCESS: '@@SERVICE_CATEGORY_DELETE/SUCESS',
    SERVICE_CATEGORY_DELETE_ERROR: '@@SERVICE_CATEGORY_DELETE/ERROR',
    SERVICE_CATEGORY_DELETE_RESET: '@@SERVICE_CATEGORY_DELETE/RESETSET',
};
export default ServiceCategoryActionTypes;
