const ProductUpchargesActionTypes = {

    // start list 
    GET_UPCHARGES_LIST: '@@GET_UPCHARGES_LIST',
    UPCHARGES_LIST_LOADING: '@@UPCHARGES_LIST/LOADING',
    UPCHARGES_LIST_SUCCESS: '@@UPCHARGES_LIST/SUCESS',
    UPCHARGES_LIST_ERROR: '@@UPCHARGES_LIST/ERROR',


    // start create 
    CREATE_UPCHARGES: '@@CREATE_UPCHARGES',
    UPCHARGES_CREATE_LOADING: '@@UPCHARGES_CREATE/LOADING',
    UPCHARGES_CREATE_SUCESS: '@@UPCHARGES_CREATE/SUCESS',
    UPCHARGES_CREATE_ERROR: '@@UPCHARGES_CREATE/ERROR',
    UPCHARGES_CREATE_RESET: '@@UPCHARGES_CREATE/RESET',


    // // start update 
    UPDATE_UPCHARGES: '@@UPDATE_UPCHARGES',
    UPCHARGES_UPDATE_LOADING: '@@UPCHARGES_UPDATE/LOADING',
    UPCHARGES_UPDATE_SUCESS: '@@UPCHARGES_UPDATE/SUCESS',
    UPCHARGES_UPDATE_ERROR: '@@UPCHARGES_UPDATE/ERROR',
    UPCHARGES_UPDATE_RESET: '@@UPCHARGES_UPDATE/RESET',


    // // start update 
    DELETE_UPCHARGES: '@@DELETE_UPCHARGES',
    UPCHARGES_DELETE_LOADING: '@@UPCHARGES_DELETE/LOADING',
    UPCHARGES_DELETE_SUCESS: '@@UPCHARGES_DELETE/SUCESS',
    UPCHARGES_DELETE_ERROR: '@@UPCHARGES_DELETE/ERROR',
    UPCHARGES_DELETE_RESET: '@@UPCHARGES_DELETE/RESETSET',

}

export default ProductUpchargesActionTypes
