const DiscountChargesReportActionTypes = {

    // start discount charges report 
    GET_DISCOUNT_CHARGES_REPORT: '@@GET_DISCOUNT_CHARGES_REPORT',
    DISCOUNT_CHARGES_REPORT_LOADING: '@@DISCOUNT_CHARGES_REPORT/LOADING',
    DISCOUNT_CHARGES_REPORT_SUCCESS: '@@DISCOUNT_CHARGES_REPORT/SUCESS',
    DISCOUNT_CHARGES_REPORT_ERROR: '@@DISCOUNT_CHARGES_REPORT/ERROR'
}
export default DiscountChargesReportActionTypes;