const LaundryPackagesActionTypes = {

    // start list 
    GET_LAUNDRY_PACKAGES_LIST: '@@GET_LAUNDRY_PACKAGES_LIST',
    LAUNDRY_PACKAGES_LIST_LOADING: '@@LAUNDRY_PACKAGES_LIST/LOADING',
    LAUNDRY_PACKAGES_LIST_SUCCESS: '@@LAUNDRY_PACKAGES_LIST/SUCESS',
    LAUNDRY_PACKAGES_LIST_ERROR: '@@LAUNDRY_PACKAGES_LIST/ERROR',


    // start create 
    CREATE_LAUNDRY_PACKAGES: '@@CREATE_LAUNDRY_PACKAGES',
    LAUNDRY_PACKAGES_CREATE_LOADING: '@@LAUNDRY_PACKAGES_CREATE/LOADING',
    LAUNDRY_PACKAGES_CREATE_SUCESS: '@@LAUNDRY_PACKAGES_CREATE/SUCESS',
    LAUNDRY_PACKAGES_CREATE_ERROR: '@@LAUNDRY_PACKAGES_CREATE/ERROR',
    LAUNDRY_PACKAGES_CREATE_RESET: '@@LAUNDRY_PACKAGES_CREATE/RESET',



    // // start update 
    UPDATE_LAUNDRY_PACKAGES: '@@UPDATE_LAUNDRY_PACKAGES',
    LAUNDRY_PACKAGES_UPDATE_LOADING: '@@LAUNDRY_PACKAGES_UPDATE/LOADING',
    LAUNDRY_PACKAGES_UPDATE_SUCESS: '@@LAUNDRY_PACKAGES_UPDATE/SUCESS',
    LAUNDRY_PACKAGES_UPDATE_ERROR: '@@LAUNDRY_PACKAGES_UPDATE/ERROR',

    // // start delete 
    DELETE_LAUNDRY_PACKAGES: '@@DELETE_LAUNDRY_PACKAGES',
    LAUNDRY_PACKAGES_DELETE_LOADING: '@@LAUNDRY_PACKAGES_DELETE/LOADING',
    LAUNDRY_PACKAGES_DELETE_SUCESS: '@@LAUNDRY_PACKAGES_DELETE/SUCESS',
    LAUNDRY_PACKAGES_DELETE_ERROR: '@@LAUNDRY_PACKAGES_DELETE/ERROR',
    LAUNDRY_PACKAGES_DELETE_RESET: '@@LAUNDRY_PACKAGES_DELETE/RESETSET',
}

export default LaundryPackagesActionTypes
