const MENU_ITEMS = [
    { key: 'navigation', label: 'Navigation', isTitle: true },
    {
        key: 'homes',
        label: 'Home',
        isTitle: false,
        icon: 'uil-home-alt',
        url: '/dashboard/ecommerce',
        // key: 'dashboards',
        // label: 'Dashboards',
        // isTitle: false,
        // icon: 'uil-home-alt',
        // badge: { variant: 'success', text: '4' },
        // children: [
        //     {
        //         key: 'ds-analytics',
        //         label: 'Analytics',
        //         url: '/dashboard/analytics',
        //         parentKey: 'dashboards',
        //     },
        //     {
        //         key: 'ds-ecommerce',
        //         label: 'Ecommerce',
        //         url: '/dashboard/ecommerce',
        //         parentKey: 'dashboards',
        //     },
        //     {
        //         key: 'ds-project',
        //         label: 'Projects',
        //         url: '/dashboard/project',
        //         parentKey: 'dashboards',
        //     },
        //     {
        //         key: 'ds-ewallet',
        //         label: 'E-Wallet',
        //         url: '/dashboard/e-wallet',
        //         parentKey: 'dashboards',
        //         badge: { variant: 'danger', text: 'New' },
        //     },
        // ],
    },
    {
        key: 'employees',
        label: 'Employee',
        isTitle: false,
        icon: 'uil-user',
        children: [
            // {
            //     key: 'employee',
            //     label: 'Employee',
            //     url: '/employee',
            //     parentKey: 'employees',
            // },
            {
                key: 'employeeTable',
                label: 'Employee',
                url: '/employeeTable',
                parentKey: 'employees',
            },
        ],
    },
    {
        key: 'transactions',
        label: 'Transactions',
        isTitle: false,
        icon: 'uil-usd-circle',

        children: [
            // {
            //     key: 'ts-orderlist',
            //     label: 'Order List',
            //     url: '/transactions/orderlist',
            //     parentKey: 'transactions',
            // },
            {
                key: 'ts-ordertable',
                label: 'Order Table',
                // icon:'bi bi-table',
                url: '/transactions/orderTable',
                parentKey: 'transactions',
            },
            // {
            //     key: 'ts-pickuprequestlist',
            //     label: 'Pickup Request List',
            //     url: '/transactions/pickuprequestlist',
            //     parentKey: 'transactions',
            // },
            {
                key: 'ts-pickup',
                label: 'Pickup Request List',
                url: '/transactions/pickup',
                parentKey: 'transactions',
            },
            // {
            //     key: 'ts-deliveryRequesList',
            //     label: 'Delivery Request List',
            //     url: '/transactions/deliveryRequeslist',
            //     parentKey: 'transactions',
            // },
            {
                key: 'ts-delivery',
                label: 'Delivery Request List',
                url: '/transactions/delivery',
                parentKey: 'transactions',
            },
            // {
            //     key: 'ts-packagesList',
            //     label: 'Packages List',
            //     url: '/transactions/packageslist',
            //     parentKey: 'transactions',
            // },
            {
                key: 'ts-package',
                label: 'Packages List',
                url: '/transactions/packages',
                parentKey: 'transactions',
            },
            // {
            //     key: 'ts-bulkinvoicelist',
            //     label: 'Bulk Invoice List',
            //     url: '/transactions/bulkinvoicelist',
            //     parentKey: 'transactions',
            // },
            {
                key: 'ts-bulkinvoice',
                label: 'Bulk Invoice List',
                url: '/transactions/bulkinvoice',
                parentKey: 'transactions',
            },
            // {
            //     key: 'ts-driverlist',
            //     label: 'Driver List',
            //     url: '/transactions/driverlist',
            //     parentKey: 'transactions',
            // },
            {
                key: 'ts-driver',
                label: 'Driver List',
                url: '/transactions/driver',
                parentKey: 'transactions',
            },
        ],
    },
    {
        key: 'productservices',
        label: 'Products & Services',
        isTitle: false,
        icon: 'dripicons-store',

        children: [
            {
                key: 'ps-pricelist',
                label: 'Price List',
                url: '/productservices/price',
                // url: '/productservices/pricelist',
                parentKey: 'productservices',
            },
            {
                key: 'ps-servicecategory',
                label: 'Service Category',
                url: '/productservices/serviceAndCategory',
                // url: '/productservices/servicecategory',
                parentKey: 'productservices',
            },
            // {
            //     key: 'ps-serviceandcategory',
            //     label: 'Services',
            //     url: '/productservices/serviceAndCategory',
            //     parentKey: 'productservices',
            // },
            {
                key: 'ps-productcategory',
                label: 'Product Category',
                // url: '/productservices/productcategory',
                url: '/productservices/products',
                parentKey: 'productservices',
            },
            // {
            //     key: 'ps-products',
            //     label: 'Products',
            //     url: '/productservices/products',
            //     parentKey: 'productservices',
            // },
            {
                key: 'ps-productbrand',
                label: 'Product Brand',
                // url: '/productservices/productbrand',
                url: '/productservices/productBrands',
                parentKey: 'productservices',
            },
            // {
            //     key: 'ps-productBrand',
            //     label: 'Product_Brand',
            //     url: '/productservices/productBrands',
            //     parentKey: 'productservices',
            // },
            {
                key: 'ps-productdefects',
                label: 'Product Defects',
                // url: '/productservices/productdefects',
                url: '/productservices/productDefect',
                parentKey: 'productservices',
            },
            // {
            //     key: 'ps-productDefect',
            //     label: 'Product_Defect',
            //     url: '/productservices/productDefect',
            //     parentKey: 'productservices',
            // },
            {
                key: 'ps-productpatterns',
                label: 'Product Patterns',
                // url: '/productservices/productpatterns',
                url: '/productservices/productPattern',
                parentKey: 'productservices',
            },
            // {
            //     key: 'ps-productPattern',
            //     label: 'Product_Pattern',
            //     url: '/productservices/productPattern',
            //     parentKey: 'productservices',
            // },
            {
                key: 'ps-productcolor',
                label: 'Product Color',
                // url: '/productservices/productcolor',
                url: '/productservices/productColors',
                parentKey: 'productservices',
            },
            // {
            //     key: 'ps-productColor',
            //     label: 'Product_Colors',
            //     url: '/productservices/productColors',
            //     parentKey: 'productservices',
            // },
            {
                key: 'ps-upcharges',
                label: 'Upcharges',
                // url: '/productservices/upcharges',
                url: '/productservices/upCharge',
                parentKey: 'productservices',
            },
            // {
            //     key: 'ps-upCharge',
            //     label: 'Up_Charges',
            //     url: '/productservices/upCharge',
            //     parentKey: 'productservices',
            // },
            {
                key: 'ps-laundrypackages',
                label: 'Laundry Packages',
                // url: '/productservices/laundrypackages',
                url: '/productservices/laundryPackage',
                parentKey: 'productservices',
            },
            // {
            //     key: 'ps-laundryPackage',
            //     label: 'Laundry_Package',
            //     url: '/productservices/laundryPackage',
            //     parentKey: 'productservices',
            // },
        ],
    },
    {
        key: 'organizationsettings',
        label: 'Organization Settings',
        isTitle: false,
        icon: 'dripicons-gear',

        children: [
            {
                key: 'os-adminprofile',
                label: 'Admin Profile',
                // url: '/organization/adminprofile',
                url: '/organization/admin',
                parentKey: 'organizationsettings',
            },
            // {
            //     key: 'os-admin',
            //     label: 'Admin',
            //     url: '/organization/admin',
            //     parentKey: 'organizationsettings',
            // },
            {
                key: 'os-generalsettings',
                label: 'General Settings',
                // url: '/organization/generalsettings',
                url: '/organization/settings',
                parentKey: 'organizationsettings',
            },
            // {
            //     key: 'os-settings',
            //     label: 'Settings',
            //     url: '/organization/settings',
            //     parentKey: 'organizationsettings',
            // },
            {
                key: 'os-smsemailsetting',
                label: 'SMS & Email Setting',
                // url: '/organization/smsemailsetting',
                url: '/organization/smsandemail',
                parentKey: 'organizationsettings',
            },
            // {
            //     key: 'os-smsandemail',
            //     label: 'SMS/Email Setting',
            //     url: '/organization/smsandemail',
            //     parentKey: 'organizationsettings',
            // },
            {
                key: 'os-groups',
                label: 'Groups',
                // url: '/organization/groups',
                url: '/organization/group',
                parentKey: 'organizationsettings',
            },
            // {
            //     key: 'os-group',
            //     label: 'Groups List',
            //     url: '/organization/group',
            //     parentKey: 'organizationsettings',
            // },
            // {
            //     key: 'os-rolepermission',
            //     label: 'Role / Permission',
            //     url: '/organization/rolepermission',
            //     parentKey: 'organizationsettings',
            // },
        ],
    },

    {
        key: 'locationsetting',
        label: 'Location Setting',
        isTitle: false,
        icon: 'dripicons-location',

        children: [
            {
                key: 'ls-storesettings',
                label: 'Store Settings',
                url: '/locationsetting/stores',
                // url: '/locationsetting/storesettings',
                parentKey: 'locationsetting',
            },
            // {
            //     key: 'ls-stores',
            //     label: 'Stores',
            //     url: '/locationsetting/stores',
            //     parentKey: 'locationsetting',
            // },
        ],
    },
    {
        key: 'payments',
        label: 'Payments',
        isTitle: false,
        icon: 'dripicons-card',

        children: [
            {
                key: 'ps-paymenttype',
                label: 'Payment Type',
                // url: '/payments/paymenttype',
                url: '/payments/paymentTypes',
                parentKey: 'payments',
            },
            // {
            //     key: 'ps-paymentTypes',
            //     label: 'Payment_Type',
            //     url: '/payments/paymentTypes',
            //     parentKey: 'payments',
            // },
            {
                key: 'ps-paymentadjustment',
                label: 'Payment Adjustment',
                // url: '/payments/paymentadjustment',
                url: '/payments/paymentAdjustments',
                parentKey: 'payments',
            },
            // {
            //     key: 'ps-paymentAdjustments',
            //     label: 'Payment_Adjustment',
            //     url: '/payments/paymentAdjustments',
            //     parentKey: 'payments',
            // },
            {
                key: 'ps-paymentsetting',
                label: 'Payment Setting',
                url: '/payments/paymentSettings',
                // url: '/payments/paymentsetting',
                parentKey: 'payments',
            },
            // {
            //     key: 'ps-paymentSettings',
            //     label: 'Payment_Setting',
            //     url: '/payments/paymentSettings',
            //     parentKey: 'payments',
            // },
            // {
            //     key: 'ps-advancesettingforstripe',
            //     label: 'Advance Setting',
            //     url: '/payments/advancesettingforstripe',
            //     parentKey: 'payments',
            // },
            // {
            //     key: 'ps-tipsetting',
            //     label: 'Tip Setting',
            //     url: '/payments/tipsetting',
            //     parentKey: 'payments',
            // },
            // {
            //     key: 'ps-paymentcharges',
            //     label: 'Payment Charges',
            //     url: '/payments/paymentcharges',
            //     parentKey: 'payments',
            // },
            {
                key: 'ps-paymentlist',
                label: 'Payment List',
                // url: '/payments/paymentlist',
                url: '/payments/paymentLists',
                parentKey: 'payments',
            },
            // {
            //     key: 'ps-paymentlists',
            //     label: 'Payment_List',
            //     url: '/payments/paymentLists',
            //     parentKey: 'payments',
            // },
        ],
    },

    {
        key: 'customer',
        label: 'Customer',
        isTitle: false,
        icon: 'uil-users-alt',

        children: [
            {
                key: 'cr-addnewcustomer',
                label: 'Add New Customer',
                // url: '/customer/addnewcustomer',
                url: '/customer/createcustomer',
                parentKey: 'customer',
            },
            // {
            //     key: 'cr-createcustomer',
            //     label: 'Create Customer',
            //     url: '/customer/createcustomer',
            //     parentKey: 'customer',
            // },
            {
                key: 'cr-customerlist',
                label: 'Customer List',
                // url: '/customer/customerlist',
                url: '/customer/customerTable',
                parentKey: 'customer',
            },
            // {
            //     key: 'cr-customerTable',
            //     label: 'Customer Table',
            //     url: '/customer/customerTable',
            //     parentKey: 'customer',
            // },
            {
                key: 'cr-customerdues',
                label: 'Customer Dues',
                url: '/customer/customerdues',
                parentKey: 'customer',
            },
        ],
    },

    {
        key: 'analytics',
        label: 'Analytics',
        isTitle: false,
        icon: 'dripicons-pulse',

        children: [
            {
                key: 'as-datewisereport',
                label: 'Datewise Report',
                url: '/analytics/datewisereport',
                parentKey: 'analytics',
            },
            {
                key: 'as-monthlyreport',
                label: 'Monthly Report',
                url: '/analytics/monthlyreport',
                parentKey: 'analytics',
            },
            {
                key: 'as-dueamountreport',
                label: 'Due Amount Report',
                url: '/analytics/dueamountreport',
                parentKey: 'analytics',
            },
            {
                key: 'as-dueorderlist',
                label: 'Due Order List',
                url: '/analytics/dueorderlist',
                parentKey: 'analytics',
            },
            {
                key: 'as-expensesreport',
                label: 'Expenses Report',
                url: '/analytics/expensesreport',
                parentKey: 'analytics',
            },
            {
                key: 'as-incomereport',
                label: 'Income Report',
                url: '/analytics/incomereport',
                parentKey: 'analytics',
            },
            {
                key: 'as-productlist',
                label: 'Product List',
                url: '/analytics/productlist',
                parentKey: 'analytics',
            },
            {
                key: 'as-productwisereport',
                label: 'Product Wise Report',
                url: '/analytics/productwisereport',
                parentKey: 'analytics',
            },
            {
                key: 'as-walletdeletehistoryreport',
                label: 'Wallet Delete History Report',
                url: '/analytics/walletdeletehistoryreport',
                parentKey: 'analytics',
            },
            {
                key: 'as-walletbalancelist',
                label: 'Wallet Balance List Report',
                url: '/analytics/walletbalancelist',
                parentKey: 'analytics',
            },
            {
                key: 'as-promocodereportlist',
                label: 'Promo Code Report',
                url: '/analytics/promocodereportlist',
                parentKey: 'analytics',
            },
            {
                key: 'as-retailproductwisereport',
                label: 'Retail Product Wise Report',
                url: '/analytics/retailproductwisereport',
                parentKey: 'analytics',
            },
            {
                key: 'as-attendancereport',
                label: 'Attendance Report',
                url: '/analytics/attendancereport',
                parentKey: 'analytics',
            },
            {
                key: 'as-discountchargesreportlist',
                label: 'Discount / Charges Report',
                url: '/analytics/discountchargesreportlist',
                parentKey: 'analytics',
            },
            {
                key: 'as-cashdayreportlist',
                label: 'Cash / Day Report',
                url: '/analytics/cashdayreportlist',
                parentKey: 'analytics',
            },
            {
                key: 'as-profitandloss',
                label: 'Profit And Loss',
                url: '/analytics/profitandloss',
                parentKey: 'analytics',
            },
            {
                key: 'as-wallethistorylist',
                label: 'Wallet History List',
                url: '/analytics/wallethistorylist',
                parentKey: 'analytics',
            },
            {
                key: 'as-taxcollectionreport',
                label: 'Tax Collection Report',
                url: '/analytics/taxcollectionreport',
                parentKey: 'analytics',
            },
            {
                key: 'as-tipreport',
                label: 'Tip Report',
                url: '/analytics/tipreport',
                parentKey: 'analytics',
            },
        ],
    },

    {
        key: 'appsetting',
        label: 'Apps',
        isTitle: false,
        icon: 'uil-apps',

        children: [
            {
                key: 'as-appsettings',
                label: 'App Setting',
                url: '/appssetting/appsettings',
                parentKey: 'appsetting',
            },
            {
                key: 'as-banner',
                label: 'Banner',
                url: '/appssetting/banner',
                parentKey: 'appsetting',
            },
            {
                key: 'as-doordashsetting',
                label: 'Doordash Setting',
                url: '/appssetting/doordashsetting',
                parentKey: 'appsetting',
            },
        ],
    },
    {
        key: 'promotion',
        label: 'Promotion',
        isTitle: false,
        icon: 'dripicons-broadcast',

        children: [
            {
                key: 'ps-promotions',
                label: 'Promotions',
                url: '/promotion/promotions',
                parentKey: 'promotion',
            },
            {
                key: 'ps-walletpromo',
                label: 'Wallet Promo',
                url: '/promotion/walletpromo',
                parentKey: 'promotion',
            },
            {
                key: 'ps-discount',
                label: 'Discount',
                url: '/promotion/discount',
                parentKey: 'promotion',
            },
            {
                key: 'ps-automatedpromo',
                label: 'Automated Promo',
                url: '/promotion/automatedpromo',
                parentKey: 'promotion',
            },
        ],
    },

    // { key: 'apps', label: 'Apps', isTitle: true },
    // {
    //     key: 'apps-calendar',
    //     label: 'Calendar',
    //     isTitle: false,
    //     icon: 'uil-calender',
    //     url: '/apps/calendar',
    // },
    // {
    //     key: 'apps-chat',
    //     label: 'Chat',
    //     isTitle: false,
    //     icon: 'uil-comments-alt',
    //     url: '/apps/chat',
    // },
    // {
    //     key: 'apps-crm',
    //     label: 'CRM',
    //     isTitle: false,
    //     badge: { variant: 'danger', text: 'New' },
    //     icon: 'uil-tachometer-fast',
    //     children: [
    //         {
    //             key: 'crm-products',
    //             label: 'Dashboard',
    //             url: '/apps/crm/dashboard',
    //             parentKey: 'apps-crm',
    //         },
    //         {
    //             key: 'crm-projects',
    //             label: 'Project',
    //             url: '/apps/crm/projects',
    //             parentKey: 'apps-crm',
    //         },
    //         {
    //             key: 'crm-orders',
    //             label: 'Orders List',
    //             url: '/apps/crm/orders',
    //             parentKey: 'apps-crm',
    //         },
    //         {
    //             key: 'crm-clients',
    //             label: 'Clients',
    //             url: '/apps/crm/clients',
    //             parentKey: 'apps-crm',
    //         },
    //         {
    //             key: 'crm-management',
    //             label: 'Management',
    //             url: '/apps/crm/management',
    //             parentKey: 'apps-crm',
    //         },
    //     ],
    // },
    // {
    //     key: 'apps-ecommerce',
    //     label: 'Ecommerce',
    //     isTitle: false,
    //     icon: 'uil-store',
    //     children: [
    //         {
    //             key: 'ecommerce-products',
    //             label: 'Products',
    //             url: '/apps/ecommerce/products',
    //             parentKey: 'apps-ecommerce',
    //         },
    //         {
    //             key: 'ecommerce-details',
    //             label: 'Products Details',
    //             url: '/apps/ecommerce/details',
    //             parentKey: 'apps-ecommerce',
    //         },
    //         {
    //             key: 'ecommerce-orders',
    //             label: 'Orders',
    //             url: '/apps/ecommerce/orders',
    //             parentKey: 'apps-ecommerce',
    //         },
    //         {
    //             key: 'ecommerce-order-details',
    //             label: 'Order Details',
    //             url: '/apps/ecommerce/order/details',
    //             parentKey: 'apps-ecommerce',
    //         },
    //         {
    //             key: 'ecommerce-customers',
    //             label: 'Customers',
    //             url: '/apps/ecommerce/customers',
    //             parentKey: 'apps-ecommerce',
    //         },
    //         {
    //             key: 'ecommerce-shopping-cart',
    //             label: 'Shopping Cart',
    //             url: '/apps/ecommerce/shopping-cart',
    //             parentKey: 'apps-ecommerce',
    //         },
    //         {
    //             key: 'ecommerce-checkout',
    //             label: 'Checkout',
    //             url: '/apps/ecommerce/checkout',
    //             parentKey: 'apps-ecommerce',
    //         },
    //         {
    //             key: 'ecommerce-sellers',
    //             label: 'Sellers',
    //             url: '/apps/ecommerce/sellers',
    //             parentKey: 'apps-ecommerce',
    //         },
    //     ],
    // },
    // {
    //     key: 'apps-email',
    //     label: 'Email',
    //     isTitle: false,
    //     icon: 'uil-envelope',
    //     children: [
    //         {
    //             key: 'email-inbox',
    //             label: 'Inbox',
    //             url: '/apps/email/inbox',
    //             parentKey: 'apps-email',
    //         },
    //         {
    //             key: 'email-read-email',
    //             label: 'Read Email',
    //             url: '/apps/email/details',
    //             parentKey: 'apps-email',
    //         },
    //     ],
    // },
    // {
    //     key: 'apps-projects',
    //     label: 'Projects',
    //     isTitle: false,
    //     icon: 'uil-briefcase',
    //     children: [
    //         {
    //             key: 'project-list',
    //             label: 'List',
    //             url: '/apps/projects/list',
    //             parentKey: 'apps-projects',
    //         },
    //         {
    //             key: 'project-details',
    //             label: 'Details',
    //             url: '/apps/projects/details',
    //             parentKey: 'apps-projects',
    //         },
    //         {
    //             key: 'project-gantt',
    //             label: 'Gantt',
    //             url: '/apps/projects/gantt',
    //             badge: { variant: 'light', text: 'New' },
    //             parentKey: 'apps-projects',
    //         },
    //         {
    //             key: 'project-create-project',
    //             label: 'Create Project',
    //             url: '/apps/projects/new',
    //             parentKey: 'apps-projects',
    //         },
    //     ],
    // },
    // {
    //     key: 'apps-social',
    //     label: 'Social Feed',
    //     isTitle: false,
    //     icon: 'uil-rss',
    //     url: '/apps/social',
    // },
    // {
    //     key: 'apps-tasks',
    //     label: 'Tasks',
    //     isTitle: false,
    //     icon: 'uil-clipboard-alt',
    //     children: [
    //         {
    //             key: 'task-list',
    //             label: 'List',
    //             url: '/apps/tasks/list',
    //             parentKey: 'apps-tasks',
    //         },
    //         {
    //             key: 'task-details',
    //             label: 'Details',
    //             url: '/apps/tasks/details',
    //             parentKey: 'apps-tasks',
    //         },
    //         {
    //             key: 'task-kanban',
    //             label: 'Kanban Board',
    //             url: '/apps/tasks/kanban',
    //             parentKey: 'apps-tasks',
    //         },
    //     ],
    // },
    // {
    //     key: 'apps-file-manager',
    //     label: 'File Manager',
    //     isTitle: false,
    //     icon: 'uil-folder-plus',
    //     url: '/apps/file',
    // },

    // { key: 'custom', label: 'Custom', isTitle: true },
    // {
    //     key: 'pages',
    //     label: 'Pages',
    //     isTitle: false,
    //     icon: 'uil-copy-alt',
    //     children: [
    //         {
    //             key: 'page-profile',
    //             label: 'Profile',
    //             url: '/pages/profile',
    //             parentKey: 'pages',
    //         },
    //         {
    //             key: 'page-profile2',
    //             label: 'Profile 2',
    //             url: '/pages/profile2',
    //             parentKey: 'pages',
    //         },
    //         {
    //             key: 'page-invoice',
    //             label: 'Invoice',
    //             url: '/pages/invoice',
    //             parentKey: 'pages',
    //         },
    //         { key: 'page-faq', label: 'FAQ', url: '/pages/faq', parentKey: 'pages' },
    //         {
    //             key: 'page-pricing',
    //             label: 'Pricing',
    //             url: '/pages/pricing',
    //             parentKey: 'pages',
    //         },
    //         {
    //             key: 'page-maintenance',
    //             label: 'Maintenance',
    //             url: '/maintenance',
    //             target: '_blank',
    //             parentKey: 'pages',
    //         },
    //         {
    //             key: 'page-error-404',
    //             label: 'Error - 404',
    //             url: '/error-404',
    //             parentKey: 'pages',
    //         },
    //         {
    //             key: 'page-error-404-alt',
    //             label: 'Error - 404-alt',
    //             url: '/pages/error-404-alt',
    //             parentKey: 'pages',
    //         },
    //         {
    //             key: 'page-error-500',
    //             label: 'Error - 500',
    //             url: '/error-500',
    //             parentKey: 'pages',
    //         },
    //         {
    //             key: 'page-starter',
    //             label: 'Starter Page',
    //             url: '/pages/starter',
    //             parentKey: 'pages',
    //         },
    //         {
    //             key: 'page-preloader',
    //             label: 'With Preloader',
    //             url: '/pages/preloader',
    //             parentKey: 'pages',
    //         },
    //         {
    //             key: 'page-timeline',
    //             label: 'Timeline',
    //             url: '/pages/timeline',
    //             parentKey: 'pages',
    //         },
    //     ],
    // },
    // {
    //     key: 'landing',
    //     label: 'Landing',
    //     isTitle: false,
    //     icon: 'uil-globe',
    //     url: '/landing',
    //     target: '_blank',
    //     badge: { variant: 'secondary', text: 'New' },
    // },

    // { key: 'components', label: 'Components', isTitle: true },
    // {
    //     key: 'base-ui',
    //     label: 'Base UI',
    //     isTitle: false,
    //     icon: 'uil-box',
    //     children: [
    //         {
    //             key: 'base-ui-accordions',
    //             label: 'Accordions',
    //             url: '/ui/base-ui/accordions',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-alerts',
    //             label: 'Alerts',
    //             url: '/ui/base-ui/alerts',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-avatars',
    //             label: 'Avatars',
    //             url: '/ui/base-ui/avatars',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-badges',
    //             label: 'Badges',
    //             url: '/ui/base-ui/badges',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-breadcrumb',
    //             label: 'Breadcrumb',
    //             url: '/ui/base-ui/breadcrumb',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-buttons',
    //             label: 'Buttons',
    //             url: '/ui/base-ui/buttons',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-cards',
    //             label: 'Cards',
    //             url: '/ui/base-ui/cards',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-carousel',
    //             label: 'Carousel',
    //             url: '/ui/base-ui/carousel',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-dropdown',
    //             label: 'Dropdowns',
    //             url: '/ui/base-ui/dropdowns',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-embedvideo',
    //             label: 'Embed Video',
    //             url: '/ui/base-ui/embedvideo',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-grid',
    //             label: 'Grid',
    //             url: '/ui/base-ui/grid',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-listgroups',
    //             label: 'List Groups',
    //             url: '/ui/base-ui/listgroups',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-modals',
    //             label: 'Modals',
    //             url: '/ui/base-ui/modals',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-notifications',
    //             label: 'Notifications',
    //             url: '/ui/base-ui/notifications',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-offcanvas',
    //             label: 'Offcanvas',
    //             url: '/ui/base-ui/offcanvas',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-paginations',
    //             label: 'Paginations',
    //             url: '/ui/base-ui/paginations',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-popovers',
    //             label: 'Popovers',
    //             url: '/ui/base-ui/popovers',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-progress',
    //             label: 'Progress',
    //             url: '/ui/base-ui/progress',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-ribbons',
    //             label: 'Ribbons',
    //             url: '/ui/base-ui/ribbons',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-spinners',
    //             label: 'Spinners',
    //             url: '/ui/base-ui/spinners',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-tabs',
    //             label: 'Tabs',
    //             url: '/ui/base-ui/tabs',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-tooltips',
    //             label: 'Tooltips',
    //             url: '/ui/base-ui/tooltips',
    //             parentKey: 'base-ui',
    //         },
    //         {
    //             key: 'base-ui-typography',
    //             label: 'Typography',
    //             url: '/ui/base-ui/typography',
    //             parentKey: 'base-ui',
    //         },
    //     ],
    // },
    // {
    //     key: 'extended-ui',
    //     label: 'Extended UI',
    //     isTitle: false,
    //     icon: 'uil-package',
    //     children: [
    //         {
    //             key: 'extended-ui-dragdrop',
    //             label: 'Drag and Drop',
    //             url: '/ui/extended/dragdrop',
    //             parentKey: 'extended-ui',
    //         },
    //         {
    //             key: 'extended-ui-rangesliders',
    //             label: 'Range Sliders',
    //             url: '/ui/extended/rangesliders',
    //             parentKey: 'extended-ui',
    //         },
    //         {
    //             key: 'extended-ui-ratings',
    //             label: 'Ratings',
    //             url: '/ui/extended/ratings',
    //             parentKey: 'extended-ui',
    //         },
    //     ],
    // },
    // {
    //     key: 'widgets',
    //     label: 'Widgets',
    //     isTitle: false,
    //     icon: 'uil-layer-group',
    //     url: '/ui/widgets',
    // },
    // {
    //     key: 'icons',
    //     label: 'Icons',
    //     isTitle: false,
    //     icon: 'uil-streering',
    //     children: [
    //         {
    //             key: 'icon-dripicons',
    //             label: 'Dripicons',
    //             url: '/ui/icons/dripicons',
    //             parentKey: 'icons',
    //         },
    //         {
    //             key: 'icon-mdiicons',
    //             label: 'Material Design',
    //             url: '/ui/icons/mdi',
    //             parentKey: 'icons',
    //         },
    //         {
    //             key: 'icon-unicons',
    //             label: 'Unicons',
    //             url: '/ui/icons/unicons',
    //             parentKey: 'icons',
    //         },
    //     ],
    // },
    // {
    //     key: 'forms',
    //     label: 'Forms',
    //     isTitle: false,
    //     icon: 'uil-document-layout-center',
    //     children: [
    //         {
    //             key: 'form-basic',
    //             label: 'Basic Elements',
    //             url: '/ui/forms/basic',
    //             parentKey: 'forms',
    //         },
    //         {
    //             key: 'form-advanced',
    //             label: 'Form Advanced',
    //             url: '/ui/forms/advanced',
    //             parentKey: 'forms',
    //         },
    //         {
    //             key: 'form-validation',
    //             label: 'Validation',
    //             url: '/ui/forms/validation',
    //             parentKey: 'forms',
    //         },
    //         {
    //             key: 'form-wizard',
    //             label: 'Wizard',
    //             url: '/ui/forms/wizard',
    //             parentKey: 'forms',
    //         },
    //         {
    //             key: 'form-upload',
    //             label: 'File Upload',
    //             url: '/ui/forms/upload',
    //             parentKey: 'forms',
    //         },
    //         {
    //             key: 'form-editors',
    //             label: 'Editors',
    //             url: '/ui/forms/editors',
    //             parentKey: 'forms',
    //         },
    //     ],
    // },
    // {
    //     key: 'charts',
    //     label: 'Charts',
    //     isTitle: false,
    //     icon: 'uil-chart',
    //     children: [
    //         {
    //             key: 'chart-apex',
    //             label: 'Apex Charts',
    //             url: '/ui/charts/apex',
    //             parentKey: 'charts',
    //         },
    //         {
    //             key: 'chart-brite',
    //             label: 'Brite Charts',
    //             url: '/ui/charts/brite',
    //             parentKey: 'charts',
    //         },
    //         {
    //             key: 'chart-chartjs',
    //             label: 'Chartjs',
    //             url: '/ui/charts/chartjs',
    //             parentKey: 'charts',
    //         },
    //     ],
    // },
    // {
    //     key: 'tables',
    //     label: 'Tables',
    //     isTitle: false,
    //     icon: 'uil-table',
    //     children: [
    //         {
    //             key: 'table-basic',
    //             label: 'Basic Tables',
    //             url: '/ui/tables/basic',
    //             parentKey: 'tables',
    //         },
    //         {
    //             key: 'table-advanced',
    //             label: 'Advanced Tables',
    //             url: '/ui/tables/advanced',
    //             parentKey: 'tables',
    //         },
    //     ],
    // },
    // {
    //     key: 'maps',
    //     label: 'Maps',
    //     isTitle: false,
    //     icon: 'uil-location-point',
    //     children: [
    //         {
    //             key: 'maps-googlemaps',
    //             label: 'Google Maps',
    //             url: '/ui/maps/googlemaps',
    //             parentKey: 'maps',
    //         },
    //         {
    //             key: 'maps-vectormaps',
    //             label: 'Vector Maps',
    //             url: '/ui/maps/vectormaps',
    //             parentKey: 'maps',
    //         },
    //     ],
    // },
    // {
    //     key: 'menu-levels',
    //     label: 'Menu Levels',
    //     isTitle: false,
    //     icon: 'uil-folder-plus',
    //     children: [
    //         {
    //             key: 'menu-levels-1-1',
    //             label: 'Level 1.1',
    //             url: '/',
    //             parentKey: 'menu-levels',
    //             children: [
    //                 {
    //                     key: 'menu-levels-2-1',
    //                     label: 'Level 2.1',
    //                     url: '/',
    //                     parentKey: 'menu-levels-1-1',
    //                     children: [
    //                         {
    //                             key: 'menu-levels-3-1',
    //                             label: 'Level 3.1',
    //                             url: '/',
    //                             parentKey: 'menu-levels-2-1',
    //                         },
    //                         {
    //                             key: 'menu-levels-3-2',
    //                             label: 'Level 3.2',
    //                             url: '/',
    //                             parentKey: 'menu-levels-2-1',
    //                         },
    //                     ],
    //                 },
    //                 {
    //                     key: 'menu-levels-2-2',
    //                     label: 'Level 2.2',
    //                     url: '/',
    //                     parentKey: 'menu-levels-1-1',
    //                 },
    //             ],
    //         },
    //         {
    //             key: 'menu-levels-1-2',
    //             label: 'Level 1.2',
    //             url: '/',
    //             parentKey: 'menu-levels',
    //         },
    //     ],
    // },
];

export default MENU_ITEMS;
