const CostomerActionTypes = {

    // start constomer list 
    GET_COSTOMER_LIST: '@@GET_COSTOMER_LIST',
    COSTOMER_LIST_LOADING: '@@COSTOMER_LIST/LOADING',
    COSTOMER_LIST_SUCCESS: '@@COSTOMER_LIST/SUCESS',
    COSTOMER_LIST_ERROR: '@@COSTOMER_LIST/ERROR',

    // start constomer create
    CUSTOMER_CREATE: '@@CUSTOMER_CREATE',
    CUSTOMER_CREATE_LOADING: '@@CUSTOMER_CREATE/LOADING',
    CUSTOMER_CREATE_SUCCESS: '@@CUSTOMER_CREATE/SUCESS',
    CUSTOMER_CREATE_RESET: '@@CUSTOMER_CREATE/RESET',
    CUSTOMER_CREATE_ERROR: '@@CUSTOMER_CREATE/ERROR',

    // start constomer update
    CUSTOMER_UPDATE: '@@CUSTOMER_UPDATE',
    CUSTOMER_UPDATE_LOADING: '@@CUSTOMER_UPDATE/LOADING',
    CUSTOMER_UPDATE_SUCCESS: '@@CUSTOMER_UPDATE/SUCESS',
    CUSTOMER_UPDATE_RESET: '@@CUSTOMER_UPDATE/RESET',
    CUSTOMER_UPDATE_ERROR: '@@CUSTOMER_UPDATE/ERROR',

    // start constomer delete
    CUSTOMER_DELETE: '@@CUSTOMER_DELETE',
    CUSTOMER_DELETE_LOADING: '@@CUSTOMER_DELETE/LOADING',
    CUSTOMER_DELETE_SUCCESS: '@@CUSTOMER_DELETE/SUCESS',
    CUSTOMER_DELETE_RESET: '@@CUSTOMER_DELETE/RESET',
    CUSTOMER_DELETE_ERROR: '@@CUSTOMER_DELETE/ERROR',


}
export default CostomerActionTypes