const ProductPatternsActionTypes = {

    // start list 
    GET_PRODUCT_PATTERNS_LIST: '@@GET_PRODUCT_PATTERNS_LIST',
    PRODUCT_PATTERNS_LIST_LOADING: '@@PRODUCT_PATTERNS_LIST_LOADING/LOADING',
    PRODUCT_PATTERNS_LIST_SUCCESS: '@@PRODUCT_PATTERNS_LIST_SUCCESS/SUCESS',
    PRODUCT_PATTERNS_LIST_ERROR: '@@PRODUCT_PATTERNS_LIST_ERROR/ERROR',


    // start create 
    CREATE_PRODUCT_PATTERNS: '@@CREATE_PRODUCT_PATTERNS',
    PRODUCT_PATTERNS_CREATE_LOADING: '@@PRODUCT_PATTERNS_CREATE_LOADING/LOADING',
    PRODUCT_PATTERNS_CREATE_SUCESS: '@@PRODUCT_PATTERNS_CREATE_SUCESS/SUCESS',
    PRODUCT_PATTERNS_CREATE_ERROR: '@@PRODUCT_PATTERNS_CREATE_ERROR/ERROR',
    PRODUCT_PATTERNS_CREATE_RESET: '@@PRODUCT_PATTERNS_CREATE_ERROR/RESET',



    // // start update 
    UPDATE_PRODUCT_PATTERNS: '@@UPDATE_PRODUCT_PATTERNS',
    PRODUCT_PATTERNS_UPDATE_LOADING: '@@PRODUCT_PATTERNS_UPDATE_LOADING/LOADING',
    PRODUCT_PATTERNS_UPDATE_SUCESS: '@@PRODUCT_PATTERNS_UPDATE_SUCESS/SUCESS',
    PRODUCT_PATTERNS_UPDATE_ERROR: '@@PRODUCT_PATTERNS_UPDATE_ERROR/ERROR',
    PRODUCT_PATTERNS_UPDATE_RESET: '@@PRODUCT_PATTERNS_UPDATE_ERROR/RESET',


    // start delete 
    DELETE_PRODUCT_PATTERNS: '@@DELETE_PRODUCT_PATTERNS',
    PRODUCT_PATTERNS_DELETE_LOADING: '@@PRODUCT_PATTERNS_DELETE/LOADING',
    PRODUCT_PATTERNS_DELETE_SUCESS: '@@PRODUCT_PATTERNS_DELETE/SUCESS',
    PRODUCT_PATTERNS_DELETE_ERROR: '@@PRODUCT_PATTERNS_DELETE/ERROR',
    PRODUCT_PATTERNS_DELETE_RESET: '@@PRODUCT_PATTERNS_DELETE/RESETSET',
}

export default ProductPatternsActionTypes
