const DeliveryRequestActionTypes = {

    GET_DELIVERY_REQUEST_LIST: '@@GET_DELIVERY_REQUEST_LIST',
    DELIVERY_REQUEST_LIST_LOADING: '@@DELIVERY_REQUEST_LIST/LOADING',
    DELIVERY_REQUEST_LIST_SUCCESS: '@@DELIVERY_REQUEST_LIST/SUCESS',
    DELIVERY_REQUEST_LIST_ERROR: '@@DELIVERY_REQUEST_LIST/ERROR',

    CREATE_DELIVERY_REQUEST: '@@CREATE_DELIVERY_REQUEST',
    DELIVERY_REQUEST_CREATE_LOADING: '@@DELIVERY_REQUEST_CREATE/LOADING',
    DELIVERY_REQUEST_CREATE_SUCCESS: '@@DELIVERY_REQUEST_CREATE/SUCESS',
    DELIVERY_REQUEST_CREATE_RESET: '@@DELIVERY_REQUEST_CREATE/RESET',
    DELIVERY_REQUEST_CREATE_ERROR: '@@DELIVERY_REQUEST_CREATE/ERROR',

}
export default DeliveryRequestActionTypes