const ProductDefectsActionTypes = {

    // start list 
    GET_DEFECT_LIST: '@@GET_DEFECT_LIST',
    DEFECT_LIST_LOADING: '@@DEFECT_LIST_LOADING/LOADING',
    DEFECT_LIST_SUCCESS: '@@DEFECT_LIST_SUCCESS/SUCESS',
    DEFECT_LIST_ERROR: '@@DEFECT_LIST_ERROR/ERROR',


    // start create 
    CREATE_DEFECT: '@@CREATE_DEFECT',
    DEFECT_CREATE_LOADING: '@@DEFECT_CREATE_LOADING/LOADING',
    DEFECT_CREATE_SUCESS: '@@DEFECT_CREATE_SUCESS/SUCESS',
    DEFECT_CREATE_RESET: '@@DEFECT_CREATE_SUCESS/RESET',
    DEFECT_CREATE_ERROR: '@@DEFECT_CREATE_ERROR/ERROR',

    // start update 
    UPDATE_DEFECT: '@@UPDATE_DEFECT',
    DEFECT_UPDATE_LOADING: '@@DEFECT_UPDATE_LOADING/LOADING',
    DEFECT_UPDATE_SUCESS: '@@DEFECT_UPDATE_SUCESS/SUCESS',
    DEFECT_UPDATE_RESET: '@@DEFECT_UPDATE_SUCESS/RESET',
    DEFECT_UPDATE_ERROR: '@@DEFECT_UPDATE_ERROR/ERROR',

    // start delete 
    DELETE_DEFECT: '@@DELETE_DEFECT',
    DEFECT_DELETE_LOADING: '@@DEFECT_DELETE/LOADING',
    DEFECT_DELETE_SUCESS: '@@DEFECT_DELETE/SUCESS',
    DEFECT_DELETE_ERROR: '@@DEFECT_DELETE/ERROR',
    DEFECT_DELETE_RESET: '@@DEFECT_DELETE/RESETSET',
}
export default ProductDefectsActionTypes

