const DatewiseReportActionTypes = {

    // start Datewise Report 
    GET_DATEWISE_REPORT: '@@GET_DATEWISE_REPORT',
    DATEWISE_REPORT_LOADING: '@@DATEWISE_REPORT/LOADING',
    DATEWISE_REPORT_SUCCESS: '@@DATEWISE_REPORT/SUCESS',
    DATEWISE_REPORT_RESET: '@@DATEWISE_REPORT/RESET',
    DATEWISE_REPORT_ERROR: '@@DATEWISE_REPORT/ERROR'
}
export default DatewiseReportActionTypes;