const WalletBalanceReportListActionTypes = {

    // start wallet balance Report List 
    GET_WALLET_BALANCE_REPORT_LIST: '@@GET_WALLET_BALANCE_REPORT_LIST',
    WALLET_BALANCE_REPORT_LIST_LOADING: '@@WALLET_BALANCE_REPORT_LIST/LOADING',
    WALLET_BALANCE_REPORT_LIST_SUCCESS: '@@WALLET_BALANCE_REPORT_LIST/SUCESS',
    WALLET_BALANCE_REPORT_LIST_ERROR: '@@WALLET_BALANCE_REPORT_LIST/ERROR'

}
export default WalletBalanceReportListActionTypes;