const CostomerActiveActionTypes = {

    // start constomer active  list 
    GET_COSTOMER_ACTIVE_LIST: '@@GET_COSTOMER_ACTIVE_LIST',
    COSTOMER_ACTIVE_LIST_LOADING: '@@COSTOMER_ACTIVE_LIST/LOADING',
    COSTOMER_ACTIVE_LIST_SUCCESS: '@@COSTOMER_ACTIVE_LIST/SUCESS',
    COSTOMER_ACTIVE_LIST_ERROR: '@@COSTOMER_ACTIVE_LIST/ERROR',

}
export default CostomerActiveActionTypes