const ProfitAndLossReportListActionTypes = {

    // start PROFIT AND LOSS REPORT 
    GET_PROFIT_AND_LOSS_REPORT_LIST: '@@GET_PROFIT_AND_LOSS_REPORT_LIST',
    PROFIT_AND_LOSS_REPORT_LIST_LOADING: '@@PROFIT_AND_LOSS_REPORT_LIST/LOADING',
    PROFIT_AND_LOSS_REPORT_LIST_SUCCESS: '@@PROFIT_AND_LOSS_REPORT_LIST/SUCESS',
    PROFIT_AND_LOSS_REPORT_LIST_ERROR: '@@PROFIT_AND_LOSS_REPORT_LIST/ERROR'
}
export default ProfitAndLossReportListActionTypes;