const PaymentAdjustmentActionTypes = {

    // start list 
    GET_PAYMENT_ADJUSTMENT_LIST: '@@GET_PAYMENT_ADJUSTMENT_TYPE_LIST',
    PAYMENT_ADJUSTMENT_LIST_LOADING: '@@PAYMENT_ADJUSTMENT_LIST/LOADING',
    PAYMENT_ADJUSTMENT_LIST_SUCCESS: '@@PAYMENT_ADJUSTMENT_LIST/SUCESS',
    PAYMENT_ADJUSTMENT_LIST_ERROR: '@@PAYMENT_ADJUSTMENT_LIST/ERROR',

    // start create 
    CREATE_PAYMENT_ADJUSTMENT: '@@CREATE_PAYMENT_ADJUSTMENT',
    PAYMENT_ADJUSTMENT_CREATE_LOADING: '@@PAYMENT_ADJUSTMENT_CREATE/LOADING',
    PAYMENT_ADJUSTMENT_CREATE_SUCESS: '@@PAYMENT_ADJUSTMENT_CREATE/SUCESS',
    PAYMENT_ADJUSTMENT_CREATE_ERROR: '@@PAYMENT_ADJUSTMENT_CREATE/ERROR',
    PAYMENT_ADJUSTMENT_CREATE_RESET: '@@PAYMENT_ADJUSTMENT_CREATE/RESET',


    // update 
    UPDATE_PAYMENT_ADJUSTMENT: '@@UPDATE_PAYMENT_ADJUSTMENT',
    PAYMENT_ADJUSTMENT_UPDATE_LOADING: '@@PAYMENT_ADJUSTMENT_UPDATE/LOADING',
    PAYMENT_ADJUSTMENT_UPDATE_SUCESS: '@@PAYMENT_ADJUSTMENT_UPDATE/SUCESS',
    PAYMENT_ADJUSTMENT_UPDATE_ERROR: '@@PAYMENT_ADJUSTMENT_UPDATE/ERROR',
    PAYMENT_ADJUSTMENT_UPDATE_RESET: '@@PAYMENT_ADJUSTMENT_UPDATE/RESET',


    // delete 
    DELETE_PAYMENT_ADJUSTMENT: '@@DELETE_PAYMENT_ADJUSTMENT',
    PAYMENT_ADJUSTMENT_DELETE_LOADING: '@@PAYMENT_ADJUSTMENT_DELETE/LOADING',
    PAYMENT_ADJUSTMENT_DELETE_SUCESS: '@@PAYMENT_ADJUSTMENT_DELETE/SUCESS',
    PAYMENT_ADJUSTMENT_DELETE_ERROR: '@@PAYMENT_ADJUSTMENT_DELETE/ERROR',
    PAYMENT_ADJUSTMENT_DELETE_RESET: '@@PAYMENT_ADJUSTMENT_DELETE/RESET',


}
export default PaymentAdjustmentActionTypes;