const GeneralSettingActionTypes = {

    GET_GENERAL_SETTING: '@@GET_GENERAL_SETTING',
    GENERAL_SETTING_LOADING: '@GENERAL_SETTING/LOADING',
    GENERAL_SETTING_SUCCESS: '@GENERAL_SETTING/SUCESS',
    GENERAL_SETTING_ERROR: '@GENERAL_SETTING/ERROR',

    GENERAL_SETTING_UPDATE: '@@GENERAL_SETTING_UPDATE',
    GENERAL_SETTING_UPDATE_LOADING: '@GENERAL_SETTING_UPDATE/LOADING',
    GENERAL_SETTING_UPDATE_SUCCESS: '@GENERAL_SETTING_UPDATE/SUCESS',
    GENERAL_SETTING_UPDATE_ERROR: '@GENERAL_SETTING_UPDATE/ERROR',
    GENERAL_SETTING_UPDATE_RESET: '@GENERAL_SETTING_UPDATE/RESET',


}
export default GeneralSettingActionTypes