const WalletHistoryReportActionTypes = {

    // start Monthly Report List 
    GET_WALLET_HISTORY_REPORT_LIST: '@@GET_WALLET_HISTORY_REPORT_LIST',
    WALLET_HISTORY_REPORT_LIST_LOADING: '@@WALLET_HISTORY_REPORT_LIST/LOADING',
    WALLET_HISTORY_REPORT_LIST_SUCCESS: '@@WALLET_HISTORY_REPORT_LIST/SUCESS',
    WALLET_HISTORY_REPORT_LIST_ERROR: '@@WALLET_HISTORY_REPORT_LIST/ERROR'

}
export default WalletHistoryReportActionTypes;