const DriverActionTypes = {

    GET_DRIVER_LIST: '@@GET_DRIVER_LIST',
    DRIVER_LIST_LOADING: '@@DRIVER_LIST/LOADING',
    DRIVER_LIST_SUCCESS: '@@DRIVER_LIST/SUCESS',
    DRIVER_LIST_ERROR: '@@DRIVER_LIST/ERROR',

}
export default DriverActionTypes