const DueAmountReportActionTypes = {

    // start Due Amount Report List 
    GET_DUE_AMOUNT_REPORT_LIST: '@@GET_DUE_AMOUNT_REPORT_LIST',
    DUE_AMOUNT_REPORT_LIST_LOADING: '@@DUE_AMOUNT_REPORT_LIST/LOADING',
    DUE_AMOUNT_REPORT_LIST_SUCCESS: '@@DUE_AMOUNT_REPORT_LIST/SUCESS',
    DUE_AMOUNT_REPORT_LIST_ERROR: '@@DUE_AMOUNT_REPORT_LIST/ERROR'

}
export default DueAmountReportActionTypes;