const WalletDeleteHistoryReportListActionTypes = {

    // start Monthly Report List 
    GET_WALLET_DELETE_HISTORY_REPORT_LIST: '@@GET_WALLET_DELETE_HISTORY_REPORT_LIST',
    WALLET_DELETE_HISTORY_REPORT_LIST_LOADING: '@@WALLET_DELETE_HISTORY_REPORT_LIST/LOADING',
    WALLET_DELETE_HISTORY_REPORT_LIST_SUCCESS: '@@WALLET_DELETE_HISTORY_REPORT_LIST/SUCESS',
    WALLET_DELETE_HISTORY_REPORT_LIST_RESET: '@@WALLET_DELETE_HISTORY_REPORT_LIST/RESET',
    WALLET_DELETE_HISTORY_REPORT_LIST_ERROR: '@@WALLET_DELETE_HISTORY_REPORT_LIST/ERROR'

}
export default WalletDeleteHistoryReportListActionTypes;