const PromoCodeReportListActionTypes = {

    // start Monthly Report List 
    GET_PROMO_CODE_REPORT_LIST: '@@GET_PROMO_CODE_REPORT_LIST',
    PROMO_CODE_REPORT_LIST_LOADING: '@@PROMO_CODE_REPORT_LIST/LOADING',
    PROMO_CODE_REPORT_LIST_SUCCESS: '@@PROMO_CODE_REPORT_LIST/SUCESS',
    PROMO_CODE_REPORT_LIST_ERROR: '@@PROMO_CODE_REPORT_LIST/ERROR'

}
export default PromoCodeReportListActionTypes;