const GroupsActionTypes = {

    GET_GROUPS_LIST: '@@GET_GROUPS_LIST',
    GROUPS_LIST_LOADING: '@GROUPS_LIST/LOADING',
    GROUPS_LIST_SUCCESS: '@GROUPS_LIST/SUCESS',
    GROUPS_LIST_ERROR: '@GROUPS_LIST/ERROR',

    GROUPS_CREATE: '@@GET_GROUPS_CREATE',
    GROUPS_CREATE_LOADING: '@GROUPS_CREATE/LOADING',
    GROUPS_CREATE_SUCCESS: '@GROUPS_CREATE/SUCESS',
    GROUPS_CREATE_ERROR: '@GROUPS_CREATE/ERROR',
    GROUPS_CREATE_RESET: '@GROUPS_CREATE/RESET',

    GROUPS_UPDATE: '@@GROUPS_UPDATE',
    GROUPS_UPDATE_LOADING: '@GROUPS_UPDATE/LOADING',
    GROUPS_UPDATE_SUCCESS: '@GROUPS_UPDATE/SUCESS',
    GROUPS_UPDATE_RESET: '@GROUPS_UPDATE/RESET',
    GROUPS_UPDATE_ERROR: '@GROUPS_UPDATE/ERROR',

    GROUPS_DELETE: '@@GROUPS_DELETE',
    GROUPS_DELETE_LOADING: '@GROUPS_DELETE/LOADING',
    GROUPS_DELETE_SUCCESS: '@GROUPS_DELETE/SUCESS',
    GROUPS_DELETE_RESET: '@GROUPS_DELETE/RESET',
    GROUPS_DELETE_ERROR: '@GROUPS_DELETE/ERROR',

}
export default GroupsActionTypes