const AppSettingActionTypes = {

    // start app Setting list 
    GET_APP_SETTING_LIST: '@@GET_APP_SETTING_LIST',
    APP_SETTING_LIST_LOADING: '@@APP_SETTING_LIST/LOADING',
    APP_SETTING_LIST_SUCCESS: '@@APP_SETTING_LIST/SUCESS',
    APP_SETTING_LIST_ERROR: '@@APP_SETTING_LIST/ERROR',

    // start app Setting update
    APP_SETTING_UPDATE: '@@APP_SETTING_UPDATE',
    APP_SETTING_UPDATE_LOADING: '@@APP_SETTING_UPDATE/LOADING',
    APP_SETTING_UPDATE_SUCCESS: '@@APP_SETTING_UPDATE/SUCESS',
    APP_SETTING_UPDATE_RESET: '@@APP_SETTING_UPDATE/RESET',
    APP_SETTING_UPDATE_ERROR: '@@APP_SETTING_UPDATE/ERROR',

}
export default AppSettingActionTypes