const WalletPromoActionTypes = {

    // start wallet promo list 
    GET_WALLET_PROMO_LIST: '@@GET_WALLET_PROMO_LIST',
    WALLET_PROMO_LIST_LOADING: '@@WALLET_PROMO_LIST/LOADING',
    WALLET_PROMO_LIST_SUCCESS: '@@WALLET_PROMO_LIST/SUCESS',
    WALLET_PROMO_LIST_ERROR: '@@WALLET_PROMO_LIST/ERROR',

    // start wallet promo create
    CREATE_WALLET_PROMO: '@@CREATE_WALLET_PROMO',
    WALLET_PROMO_CREATE_LOADING: '@@WALLET_PROMO_CREATE/LOADING',
    WALLET_PROMO_CREATE_SUCCESS: '@@WALLET_PROMO_CREATE/SUCESS',
    WALLET_PROMO_CREATE_RESET: '@@WALLET_PROMO_CREATE/RESET',
    WALLET_PROMO_CREATE_ERROR: '@@WALLET_PROMO_CREATE/ERROR',

    // start wallet promo detail
    DETAIL_WALLET_PROMO: '@@DETAIL_WALLET_PROMO',
    WALLET_PROMO_DETAIL_LOADING: '@@WALLET_PROMO_DETAIL/LOADING',
    WALLET_PROMO_DETAIL_SUCCESS: '@@WALLET_PROMO_DETAIL/SUCESS',
    WALLET_PROMO_DETAIL_RESET: '@@WALLET_PROMO_DETAIL/RESET',
    WALLET_PROMO_DETAIL_ERROR: '@@WALLET_PROMO_DETAIL/ERROR',

    // start wallet promo update
    UPDATE_WALLET_PROMO: '@@UPDATE_WALLET_PROMO',
    WALLET_PROMO_UPDATE_LOADING: '@@WALLET_PROMO_UPDATE/LOADING',
    WALLET_PROMO_UPDATE_SUCCESS: '@@WALLET_PROMO_UPDATE/SUCESS',
    WALLET_PROMO_UPDATE_RESET: '@@WALLET_PROMO_UPDATE/RESET',
    WALLET_PROMO_UPDATE_ERROR: '@@WALLET_PROMO_UPDATE/ERROR',

    // start wallet promo delete 
    DELETE_WALLET_PROMO: '@@DELETE_WALLET_PROMO',
    WALLET_PROMO_DELETE_LOADING: '@@WALLET_PROMO_DELETE/LOADING',
    WALLET_PROMO_DELETE_SUCCESS: '@@WALLET_PROMO_DELETE/SUCESS',
    WALLET_PROMO_DELETE_RESET: '@@WALLET_PROMO_DELETE/RESET',
    WALLET_PROMO_DELETE_ERROR: '@@WALLET_PROMO_DELETE/ERROR',


}
export default WalletPromoActionTypes