const AutomatedPromoActionTypes = {

    // start automated promo list 
    GET_AUTOMATED_PROMO_LIST: '@@GET_AUTOMATED_PROMO_LIST',
    AUTOMATED_PROMO_LIST_LOADING: '@@AUTOMATED_PROMO_LIST/LOADING',
    AUTOMATED_PROMO_LIST_SUCCESS: '@@AUTOMATED_PROMO_LIST/SUCESS',
    AUTOMATED_PROMO_LIST_ERROR: '@@AUTOMATED_PROMO_LIST/ERROR',

    // start automated promo create
    CREATE_AUTOMATED_PROMO: '@CREATE_AUTOMATED_PROMO',
    AUTOMATED_PROMO_CREATE_LOADING: '@@AUTOMATED_PROMO_CREATE/LOADING',
    AUTOMATED_PROMO_CREATE_SUCCESS: '@@AUTOMATED_PROMO_CREATE/SUCESS',
    AUTOMATED_PROMO_CREATE_RESET: '@@AUTOMATED_PROMO_CREATE/RESET',
    AUTOMATED_PROMO_CREATE_ERROR: '@@AUTOMATED_PROMO_CREATE/ERROR',

    // start automated promo detail
    DETAIL_AUTOMATED_PROMO: '@DETAIL_AUTOMATED_PROMO',
    AUTOMATED_PROMO_DETAIL_LOADING: '@@AUTOMATED_PROMO_DETAIL/LOADING',
    AUTOMATED_PROMO_DETAIL_SUCCESS: '@@AUTOMATED_PROMO_DETAIL/SUCESS',
    AUTOMATED_PROMO_DETAIL_RESET: '@@AUTOMATED_PROMO_DETAIL/RESET',
    AUTOMATED_PROMO_DETAIL_ERROR: '@@AUTOMATED_PROMO_DETAIL/ERROR',

    // start automated promo update
    UPDATE_AUTOMATED_PROMO: '@UPDATE_AUTOMATED_PROMO',
    AUTOMATED_PROMO_UPDATE_LOADING: '@@AUTOMATED_PROMO_UPDATE/LOADING',
    AUTOMATED_PROMO_UPDATE_SUCCESS: '@@AUTOMATED_PROMO_UPDATE/SUCESS',
    AUTOMATED_PROMO_UPDATE_RESET: '@@AUTOMATED_PROMO_UPDATE/RESET',
    AUTOMATED_PROMO_UPDATE_ERROR: '@@AUTOMATED_PROMO_UPDATE/ERROR',

    // start automated promo delete
    DELETE_AUTOMATED_PROMO: '@@DELETE_AUTOMATED_PROMO',
    AUTOMATED_PROMO_DELETE_LOADING: '@@AUTOMATED_PROMO_DELETE/LOADING',
    AUTOMATED_PROMO_DELETE_SUCCESS: '@@AUTOMATED_PROMO_DELETE/SUCESS',
    AUTOMATED_PROMO_DELETE_RESET: '@@AUTOMATED_PROMO_DELETE/RESET',
    AUTOMATED_PROMO_DELETE_ERROR: '@@AUTOMATED_PROMO_DELETE/ERROR',


}
export default AutomatedPromoActionTypes