const AdvanceSettingForStripeActionTypes = {

    // start list 
    UPDATE_ADVANCE_SETTING_FOR_STRIPE: '@@UPDATE_ADVANCE_SETTING_FOR_STRIPE',
    ADVANCE_SETTING_FOR_STRIPE_LOADING: '@@ADVANCE_SETTING_FOR_STRIPE/LOADING',
    ADVANCE_SETTING_FOR_STRIPE_SUCCESS: '@@ADVANCE_SETTING_FOR_STRIPE/SUCESS',
    ADVANCE_SETTING_FOR_STRIPE_ERROR: '@@ADVANCE_SETTING_FOR_STRIPE/ERROR',

}
export default AdvanceSettingForStripeActionTypes