const AdminProfileActionTypes = {

    // start admin list 
    GET_ADMIN_PROFILE: '@@GET_ADMIN_PROFILE',
    ADMIN_PROFILE_LOADING: '@@ADMIN_PROFILE/LOADING',
    ADMIN_PROFILE_SUCCESS: '@@ADMIN_PROFILE/SUCESS',
    ADMIN_PROFILE_RESET: '@@ADMIN_PROFILE/RESET',
    ADMIN_PROFILE_ERROR: '@@ADMIN_PROFILE/ERROR',

    // start admin update
    ADMIN_PROFILE_UPDATE: '@@ADMIN_PROFILE_UPDATE',
    ADMIN_PROFILE_UPDATE_LOADING: '@@ADMIN_PROFILE_UPDATE/LOADING',
    ADMIN_PROFILE_UPDATE_SUCCESS: '@@ADMIN_PROFILE_UPDATE/SUCESS',
    ADMIN_PROFILE_UPDATE_RESET: '@@ADMIN_PROFILE_UPDATE/RESET',
    ADMIN_PROFILE_UPDATE_ERROR: '@@ADMIN_PROFILE_UPDATE/ERROR',

}
export default AdminProfileActionTypes