const BannerListActionTypes = {

    // start bannerlist 
    GET_BANNER_LIST: '@@GET_BANNER_LIST',
    BANNER_LIST_LOADING: '@@BANNER_LIST/LOADING',
    BANNER_LIST_SUCCESS: '@@BANNER_LIST/SUCESS',
    BANNER_LIST_ERROR: '@@BANNER_LIST/ERROR',

    // start banner create
    BANNER_CREATE: '@@BANNER_CREATE',
    BANNER_CREATE_LOADING: '@@BANNER_CREATE/LOADING',
    BANNER_CREATE_SUCCESS: '@@BANNER_CREATE/SUCESS',
    BANNER_CREATE_RESET: '@@BANNER_CREATE/RESET',
    BANNER_CREATE_ERROR: '@@BANNER_CREATE/ERROR',

    // start banner Details
    BANNER_DETAIL: '@@BANNER_DETAIL',
    BANNER_DETAIL_LOADING: '@@BANNER_DETAIL/LOADING',
    BANNER_DETAIL_SUCCESS: '@@BANNER_DETAIL/SUCESS',
    BANNER_DETAIL_RESET: '@@BANNER_DETAIL/RESET',
    BANNER_DETAIL_ERROR: '@@BANNER_DETAIL/ERROR',

    // start banner Update
    BANNER_UPDATE: '@@BANNER_UPDATE',
    BANNER_UPDATE_LOADING: '@@BANNER_UPDATE/LOADING',
    BANNER_UPDATE_SUCCESS: '@@BANNER_UPDATE/SUCESS',
    BANNER_UPDATE_RESET: '@@BANNER_UPDATE/RESET',
    BANNER_UPDATE_ERROR: '@@BANNER_UPDATE/ERROR',

    // start banner delete
    BANNER_DELETE: '@@BANNER_DELETE',
    BANNER_DELETE_LOADING: '@@BANNER_DELETE/LOADING',
    BANNER_DELETE_SUCCESS: '@@BANNER_DELETE/SUCESS',
    BANNER_DELETE_RESET: '@@BANNER_DELETE/RESET',
    BANNER_DELETE_ERROR: '@@BANNER_DELETE/ERROR',

}
export default BannerListActionTypes