const ProductWiseReportListActionTypes = {

    // start Monthly Report List 
    GET_PRODUCT_WISE_REPORT_LIST: '@@GET_PRODUCT_WISE_REPORT_LIST',
    PRODUCT_WISE_REPORT_LIST_LOADING: '@@PRODUCT_WISE_REPORT_LIST/LOADING',
    PRODUCT_WISE_REPORT_LIST_SUCCESS: '@@PRODUCT_WISE_REPORT_LIST/SUCESS',
    PRODUCT_WISE_REPORT_LIST_RESET: '@@PRODUCT_WISE_REPORT_LIST/RESET',
    PRODUCT_WISE_REPORT_LIST_ERROR: '@@PRODUCT_WISE_REPORT_LIST/ERROR'

}
export default ProductWiseReportListActionTypes;